---

- name: Install kube-bench
  yum:
    name: "{{ kube_bench_github_url }}/releases/download/v{{ kube_bench_version }}/kube-bench_{{ kube_bench_version }}_linux_amd64.rpm"
    state: present

- name: Create kube-bench workdir
  file:
    path: "{{ kube_bench_workdir }}"
    state: directory

- name: Copy kube-bench configuration
  copy:
    src: cfg
    dest: "{{ kube_bench_workdir }}"

- name: Run kube-bench
  shell: "/usr/local/bin/kube-bench {{ kube_bench_sub_command }} --json --logtostderr --outputfile {{ kube_bench_report_name }}"
  args:
    chdir: "{{ kube_bench_workdir }}"
    creates: "{{ kube_bench_report_name }}"

- name: Push report to S3 compatible destination
  aws_s3:
    bucket: "{{ kube_bench_s3_bucket_name }}"
    object: "{{ kube_bench_s3_object_path }}/{{ kube_bench_report_name }}"
    src: "{{ kube_bench_workdir }}/{{ kube_bench_report_name }}"
    mode: put
  when: kube_bench_s3_transfer

...
