image: centos:7
variables:
  ANSIBLE_FORCE_COLOR: "true"

stages:
- tests


sanity:
  stage: tests
  services:
  - docker:19.03.1-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - yum update -y && yum install -y epel-release openssh-clients git docker
    - yum install -y python-pip
    - pip install ansible==2.9.2
    - mkdir -p ../ansible_collections/sfr/
    - mv ../sfr-bench ../ansible_collections/sfr/harbor
      #    - cd harbor/ansible_collections/sfr/harbor
  script:
    - ansible-test sanity --docker
    - mv ../ansible_collections/sfr/harbor ../sfr-bench
