image: rrey/ansible-collection-runner:0.2
variables:
  ANSIBLE_FORCE_COLOR: "true"

stages:
- tests


sanity:
  stage: tests
  services:
  - docker:19.03.1-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - mkdir -p ../ansible_collections/sfr/
    - mv ../sfr-bench ../ansible_collections/sfr/harbor
    - mkdir /builds/rrey-octo/sfr-bench
    - pip3 install -r requirements.txt
  script:
    - ansible --version
    - ansible-test sanity --skip-test pylint
