image: registry.pic.services.prod/rhel7/rhel-sfr:latest
variables:
  ANSIBLE_FORCE_COLOR: "true"

stages:
- tests
- build
- publish


sanity:
  stage: tests
  before_script:
    - yum update -y && yum install -y python3 openssh-clients git
    - pip3 install -r requirements.txt
  script:
    - ansible --version
    - ansible-test sanity --python 3.6 --skip-test shebang

integration:
  stage: tests
  before_script:
    - yum update -y && yum install -y python3 openssh-clients git
    - pip3 install -r requirements.txt
    - ./scripts/set_harbor_vars.sh
  script:
    - ansible --version
    - ansible-test integration --python 3.6 harbor_project harbor_retention

#units:
#  stage: tests
#  before_script:
#    - yum update -y && yum install -y python3 openssh-clients git
#    - pip3 install -r requirements.txt
#  script:
#    - ansible --version
#    - ansible-test units --python 3.6

build collection:
  stage: build
  before_script:
    - yum update -y && yum install -y python3 openssh-clients git
    - pip3 install -r requirements.txt
    - mkdir artefact/
  script:
    - ansible --version
    - ansible-galaxy collection build --output-path artefact/
  artifacts:
    paths:
    - artefact/
    expire_in: 1 day

publish collection:
  stage: publish
  before_script:
    - yum update -y && yum install -y python3 openssh-clients git
    - pip3 install -r requirements.txt
  variables:
    COLLECTION_PATH: "artefact/sfr-harbor-${CI_COMMIT_TAG}.tar.gz"
    NEXUS_COLLECTION_PATH: "valentine/ansible_collections"
  script:
    - |
      if [ ! -f "${COLLECTION_PATH}" ]; then
          echo "Collection $COLLECTION_PATH archive not found, did you update the galaxy.yml with the proper version?" 
          exit 1
      fi
    - curl -u $NEXUS_USER:$NEXUS_PASSWORD --upload-file ${COLLECTION_PATH} $NEXUS_REPO/$NEXUS_COLLECTION_PATH/sfr-harbor-${CI_COMMIT_TAG}.tar.gz
  only:
    - tags
